version: "3.9"

volumes:
  redis:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly no --requirepass 12345678x@X
    ports:
      - 6379
    volumes:
      - redis:/data
      - ./redis_conf:/usr/local/etc/redis
